{% set name = "draco" %}
{% set version = "1.5.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/google/draco.git  
  git_rev: {{ version }}
  patches:
    - start-group.patch

build:
  number: 1
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}

test:
  commands:
    - draco_encoder -h
    - draco_transcoder -h

about:
  home: https://github.com/google/draco/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A library for compressing and decompressing 3D geometric meshes and point clouds
  description: |
    A library for compressing and decompressing 3D geometric meshes and point clouds
  doc_url: https://google.github.io/draco/
  dev_url: https://github.com/google/draco

extra:
  recipe-maintainers:
    - hobu
    - chambbj
