{% set name = "draco" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google/draco/archive/{{ version }}.tar.gz
  sha256: a5e0e923e6ddc087f6a4487499eadb9014d1e32ed4495bb10b663b9216495fab

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}

test:
  commands:
    - draco_encoder -h

about:
  home: https://github.com/google/draco/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A library for compressing and decompressing 3D geometric meshes and point clouds
  description: |
    A library for compressing and decompressing 3D geometric meshes and point clouds
  doc_url: https://google.github.io/draco/
  dev_url: https://github.com/google/draco

extra:
  recipe-maintainers:
    - hobu
    - chambbj
